# [Task]: T007
# [Spec]: F-010 (R-010.2)
# [Description]: Dapr subscription for task-events topic
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: task-events-subscription
  namespace: todo-app
spec:
  pubsubname: kafka-pubsub
  topic: task-events
  route: /api/events/task
scopes:
  - recurring-service
