# [Task]: T008
# [Spec]: F-009 (R-009.2)
# [Description]: Dapr subscription for reminders topic
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: reminders-subscription
  namespace: todo-app
spec:
  pubsubname: kafka-pubsub
  topic: reminders
  route: /api/reminders/handle
scopes:
  - notification-service
